version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=auth_service
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - JWT_SECRET=${JWT_SECRET}

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=auth_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: