version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - auth-network
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    container_name: auth-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - auth-network
    depends_on:
      - auth-service

  postgres:
    image: postgres:14-alpine
    container_name: auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - auth-network
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: auth-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - auth-network
    ports:
      - "6379:6379"

networks:
  auth-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: